export const GET_HOTELS_LOAD = "GET_HOTELS_LOAD";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAIL = "GET_HOTELS_FAIL";

export const GET_HOTEL_BYID_LOAD = "GET_HOTEL_BYID_LOAD";
export const GET_HOTEL_BYID_SUCCESS = "GET_HOTEL_BYID_SUCCESS";
export const GET_HOTEL_BYID_FAIL = "GET_HOTEL_BYID_FAIL";

export const ADD_HOTEL_LOAD = "ADD_HOTEL_LOAD";
export const ADD_HOTEL_SUCCESS = "ADD_HOTEL_SUCCESS";
export const ADD_HOTEL_FAIL = "ADD_HOTEL_FAIL";

export const DELETE_HOTEL_LOAD = "DELETE_HOTEL_LOAD";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL";

export const EDIT_HOTEL_LOAD = "EDIT_HOTEL_LOAD";
export const EDIT_HOTEL_SUCCESS = "EDIT_HOTEL_SUCCESS";
export const EDIT_HOTEL_FAIL = "EDIT_HOTEL_FAIL";



export const GET_MY_HOTELS_LOAD = "GET_MY_HOTELS_LOAD";
export const GET_MY_HOTELS_SUCCESS = "GET_MY_HOTELS_SUCCESS";
export const GET_MY_HOTELS_FAIL = "GET_MY_HOTELS_FAIL";